---

apiVersion: client.authentication.k8s.io/v1beta1


kind: Deployment

metadata:

 name: yolo5-deployment

spec:

 replicas: 2

 selector:

   matchLabels:

     app: yolo5-app

 template:

   metadata:

     labels:

       app: yolo5-app

   spec:

     containers:

       - name: yolo5-app

         image: 854171615125.dkr.ecr.us-west-1.amazonaws.com/gayatri-yolo5:${BUILD_NUMBER}


         ports:

           - containerPort: 8082

---

apiVersion: client.authentication.k8s.io/v1beta1


kind: Service

metadata:

 name: yolo5-service

spec:

 selector:

   app: yolo5-app

 ports:

   - port: 8082

     targetPort: 8082